# Input
dataset_name: "conference"
ontology_source_name: "cmt"
ontology_target_name: "conference"

seeds: 1420172

# ==============================
# Preprocessing module
# ==============================
preprocessing:
  modularizer_type: "pagerank"
  max_length_pagerank: 15
  depth: 1
  max_length_subgraph: 20
  max_length_target_sample: 3000
  include_instances: False
  include_assertions: False
  include_restrictions: False
  relations_to_remove: ["disjointWith"]

verbalizer_type:
  candidate_generator: "base"
  matcher: "base"

# ==============================
# Candidate Generation module
# ==============================
candidate_generation:
  embedding_model_name: "Qwen/Qwen3-Embedding-8B"
  backend: "transformers"
  batch_size: 2
  padding_side: "left"
  max_length: 16384
  padding: True
  truncation: True
  use_cuda: True
  max_similarities: 5
  max_length_similarities: 20
  relations_to_remove: ["disjointWith"]

# ==============================
# Matching module
# ==============================
matching:
  llm_model: "Qwen/Qwen3-14B"
  backend: "vllm"
  device: "cuda"
  dtype: "float16"
  max_model_len: 32768
  max_num_batched_tokens: 32768
  temperature: 1.0
  top_k: 0.0
  top_p: 1.0
  k: 1                   # sample generated by prompt
  max_num_seq: 2
  tensor_parallel_size: 1
  padding_side: "left"